MYSQL_USERNAME = 'pubmed'
MYSQL_PASSWORD = 'Dummy@123'
MYSQL_TABLENAME = 'cord_19.NIH_test_2'
CSV_DIRNAME = 'csv'
ELASTICSEARCH_INDEXNAME = 'nih_2'
JDBC_JARNAME = '/usr/share/java/mysql-connector-java-8.0.11.jar'
LOGSTASH_BINNAME = '/usr/share/logstash/bin/logstash'
